# Generated by Django 4.2.11 on 2026-03-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('myhome', 'MyHome'), ('lh', 'LH'), ('applyhome', 'ApplyHome')], max_length=50)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('running', '진행중'), ('success', '성공'), ('failed', '실패'), ('partial', '부분성공')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('created_items', models.IntegerField(default=0)),
                ('updated_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='crawler_cra_source_3e0ac0_idx'), models.Index(fields=['started_at'], name='crawler_cra_started_73e111_idx')],
            },
        ),
    ]
