# Generated by Django 4.2.11 on 2026-03-30 04:36

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group', models.CharField(choices=[('youth', '청년'), ('newlywed', '신혼부부'), ('general', '일반'), ('student', '대학생'), ('senior', '고령자'), ('welfare', '주거급여수급자')], db_index=True, max_length=50)),
                ('priority_level', models.IntegerField(default=0)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('income_limit_percentage', models.IntegerField(default=100, help_text='도시근로자 월평균소득 기준 (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('asset_limit', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_limit', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('special_conditions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['supply_unit', 'priority_level'],
            },
        ),
        migrations.CreateModel(
            name='HousingComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('housing_type', models.CharField(choices=[('happy', '행복주택'), ('national', '국민임대'), ('permanent', '영구임대'), ('purchase', '매입임대'), ('jeonse', '전세임대'), ('public_support', '공공지원민간임대')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('total_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('recruitment_number', models.CharField(blank=True, max_length=100)),
                ('target_groups', models.JSONField(default=list, help_text="e.g., ['youth', 'newlywed']")),
                ('total_households', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('apply_start', models.DateTimeField()),
                ('apply_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '모집중'), ('upcoming', '모집예정'), ('closed', '마감'), ('archived', '과거이력')], db_index=True, max_length=20)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('announcement_url', models.URLField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housing_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='housing.housingcomplex')),
            ],
            options={
                'ordering': ['-apply_end'],
            },
        ),
        migrations.CreateModel(
            name='SupplyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=50)),
                ('unit_name', models.CharField(blank=True, max_length=100)),
                ('exclusive_area', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('supply_area', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_units', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_base', models.BigIntegerField(help_text='기본보증금', validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_min', models.BigIntegerField(help_text='최소전환보증금', validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_max', models.BigIntegerField(help_text='최대전환보증금', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_rent', models.BigIntegerField(help_text='기본월임대료', validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_at_min', models.BigIntegerField(help_text='최소전환월임대료', validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_at_max', models.BigIntegerField(help_text='최대전환월임대료', validators=[django.core.validators.MinValueValidator(0)])),
                ('management_fee', models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority_order', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_units', to='housing.recruitment')),
            ],
            options={
                'ordering': ['recruitment', 'priority_order'],
            },
        ),
        migrations.AddIndex(
            model_name='housingcomplex',
            index=models.Index(fields=['housing_type', 'is_active'], name='housing_hou_housing_8dd3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='housingcomplex',
            index=models.Index(fields=['district', 'is_active'], name='housing_hou_distric_59c543_idx'),
        ),
        migrations.AddIndex(
            model_name='housingcomplex',
            index=models.Index(fields=['region', 'is_active'], name='housing_hou_region_fd9875_idx'),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='supply_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='housing.supplyunit'),
        ),
        migrations.AddIndex(
            model_name='supplyunit',
            index=models.Index(fields=['recruitment', 'unit_type'], name='housing_sup_recruit_d5eb51_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['housing_complex', 'status'], name='housing_rec_housing_05658e_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['apply_end'], name='housing_rec_apply_e_c67910_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibility',
            index=models.Index(fields=['supply_unit', 'target_group'], name='housing_eli_supply__a47da9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eligibility',
            unique_together={('supply_unit', 'target_group')},
        ),
    ]
