# Generated by Django 4.2.11 on 2026-03-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingcomplex',
            name='housing_type',
            field=models.CharField(choices=[('happy', '행복주택'), ('national', '국민임대'), ('permanent', '영구임대'), ('purchase', '매입임대'), ('jeonse', '전세임대'), ('public_support', '공공지원민간임대'), ('public_sale', '공공분양'), ('private_sale', '민간분양')], max_length=50),
        ),
    ]
