# Generated by Django 4.2.11 on 2026-04-02 02:30

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_housingcomplex_housing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source', models.CharField(choices=[('naver', '네이버부동산'), ('zigbang', '직방'), ('dabang', '다방'), ('peterpan', '피터팬')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('oneroom', '원룸'), ('tworoom', '투룸+'), ('officetel', '오피스텔'), ('villa', '빌라/다세대'), ('apt', '아파트')], db_index=True, max_length=20)),
                ('trade_type', models.CharField(choices=[('jeonse', '전세'), ('monthly', '월세')], db_index=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('deposit', models.BigIntegerField(help_text='보증금 (원)', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_rent', models.BigIntegerField(default=0, help_text='월세 (원)', validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_fee', models.IntegerField(default=0, help_text='관리비 (원)', validators=[django.core.validators.MinValueValidator(0)])),
                ('exclusive_area', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('building_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('detail_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='housing_ren_source_5c6af5_idx'), models.Index(fields=['room_type', 'trade_type', 'is_active'], name='housing_ren_room_ty_5ae12a_idx'), models.Index(fields=['district', 'is_active'], name='housing_ren_distric_6184a8_idx'), models.Index(fields=['region', 'is_active'], name='housing_ren_region_e2c7c0_idx'), models.Index(fields=['deposit'], name='housing_ren_deposit_455088_idx')],
            },
        ),
    ]
